tool: 0.0.1
name: gantt

rules:
  text: ([a-zA-Z0-9 ]+)
  title: text
  -----: ---+
  bar: \s*=*
  id: (\d+)
  ref: "\\[id\\]"
  row: "text \\| (bar \\*?) (?: ref | text | ())? \\n?"
  rows: "(?: row)+"

block:
  def: | 
    ref: text
  gantt: |
      title
      -----
      rows

---

name: lang2
d: 2
