name: gantt

rules:
  text: |
    [a-zA-Z0-9 ]*
  title: (text) \n
  <->: \ *
  milestone: |
    (?| \* (text) | () (?: text))
  -----: ---+ \n
  bar: (<-> =*)
  row: |
    (text) \| bar milestone \n
  rows: |
    (?: row)+
  titles: |
    (?: <-> \| (text))+ \n
  label: |
    ([a-zA-Z0-9\-]*)
  caption: (text) \n?

tokens:
  landscape: |
    \[ - \]
  portrait: |
    \[ \| \]
  gantt: |
    title
    -----
    titles
    rows
    -----
    label: caption

code:
  setup: |
    doc = lambda content: r'''
    \documentclass{article}
    \usepackage[utf8]{inputenc}
    \usepackage[margin = 2.5cm]{geometry}
    \usepackage{pgfgantt}
    \usepackage{pdflscape}

    \begin{document}
    
    %s

    \end{document}
    ''' % content
    
    lscape = lambda content: r'''
    \begin{landscape}

    %s

    \end{landscape}
    ''' % content

    is_lscape = False
    orien = [r'\textwidth', r'\columnwidth']

    gantt = lambda width, content, fig_label, caption: r'''
    \begin{figure}
    \noindent\resizebox{%s}{!}{
    \begin{ganttchart}[
      vgrid, 
      hgrid, 
      x unit = 1cm, 
      y unit chart= 0.9cm, 
      bar/.append style={fill = lightgray}]{1}{%s}

    %s

    \end{ganttchart}
    }
    \label{%s}
    \caption{%s}
    \end{figure}''' % (orien[is_lscape], width, content, fig_label, caption)

    gantt_title = lambda title, width: r'\gantttitle{%s}{%s}' % (title, width)
    gantt_bar = lambda label, start, end: r'\ganttbar{%s}{%s}{%s}' % (label, start, end)
    gantt_milestone = lambda text, pos: r'\ganttmilestone[inline]{%s}{%s}' % (text, pos)

    content = ''
    current = ''

    def update_content():
      global content, current
      if is_lscape:
        content += lscape(current)
      else:
        content += current
      current = ''
  
  landscape: |
    update_content()
    is_lscape = True
  
  portrait: |
    update_content()
    is_lscape = False
  
  gantt: |
    _, title, titles, labels, bars, milestones, fig_label, caption = captures
    width = len(max(bars, key=len))
    width += len(titles) - (width % len(titles))
    t_width = width // len(titles)

    rows = len(labels)
    fig_label = fig_label[0]
    caption = caption[0].strip()
    
    _content = gantt_title(title[0].strip(), width) + r'\\' + '\n'

    for title in titles:
      _content += gantt_title(title.strip(), t_width)
    
    _content += r'\\' + '\n'

    for row in range(rows):
      label = labels[row].strip()
      start = bars[row].find('=')
      end = len(bars[row])
      m = milestones[row]

      if start != -1:
        _content += gantt_bar(label, start + 1, end)

      if m != '':
        _content += gantt_milestone(m[1:].strip(), end)
      
      if row == rows - 1:
        _content += '\n'
      else:
        _content += r'\\' + '\n'
    
    current += gantt(width, _content, fig_label, caption)
  
  default: pass
  
  result: |
    update_content()
    document = doc(content)
    with open(f'{src.split(".")[0]}.tex', 'w') as file:
      file.write(document)
---

